### ISSUE TITLE
Additional events

### ISSUE THREAD

**Issue by erickskrauch** [voskobovich/yii2-many-to-many-behavior#16]
Why not make the events beforeSaveRelation($relationName), afterSaveRelation($relationName), beforeSaveRelations() and afterSaveRelations() ?

This would be useful for post-processing is already stored in the database.

**Comment by voskobovich** [comment]
Please, give a practical example of the problem.

**Comment by ErickSkrauch** [comment]
У меня есть поведение, которое присоединяется к таблице и ожидает события обновления\создания\удаления для выполнения синхронизации её с индексом в ElasticSearch. Всё работает хорошо, но синхронизация отношений выполняется неправильно (то есть из прошлого, до того, как отработает ваше поведение).

Соответственно было бы неплохо, чтобы поведение имело ряд своих событий для того, чтобы можно было начать синхронизацию индекса ElasticSearch строго после сохранения всех отношений.

Я создам форк с реализацией в любом случае, т.к. этот функционал мне нужен, но для начала решил предложить добавить сюда.

**Comment by voskobovich** [comment]
Предлагаю тебе реализовать этот функционал и предложить решение (отправить fork).
Мы посмотрим и совместно доработаем решение до публикации версии.

**Comment by ErickSkrauch** [comment]
Договорились.

**Comment by voskobovich** [comment]
Как дела с событиями?

**Comment by ErickSkrauch** [comment]
Проект сдали, необходимость отпала :D

Но если серьёзно, то функционал всё же полезный, так что постараюсь так или иначе реализовать это.
