### ISSUE TITLE
customDeleteCondition и like condition

### ISSUE THREAD

**Issue by sosnovski** [voskobovich/yii2-many-to-many-behavior#27]
Подскажите, можно ли задать каким нибудь образом подобное условие?:
```php
'customDeleteCondition' => [
    'like', 'name', '%str%'
]
```
Сейчас возможно, наколько я понял, задавать условия только вида:
```php
'customDeleteCondition' => [
    'name' => 'str',
]

**Comment by voskobovich** [comment]
Поддерживаются все стандартные условия yii2
https://github.com/voskobovich/yii2-many-to-many-behavior/blob/master/src/ManyToManyBehavior.php#L148

Дока: http://www.yiiframework.com/doc-2.0/yii-db-command.html#delete()-detail

**Comment by sosnovski** [comment]
Т.е. условие like не возможно использовать?

**Comment by voskobovich** [comment]
Почему же? Я не пробовал лично, но из документации следует что можно.
Ты попробуй следовать документации, если будет ошибка подробно напиши что ты делал и какая ошибка.

**Comment by voskobovich** [comment]
Напиши, пожалуйста, результаты теста. 
Спасибо!
