### ISSUE TITLE
Сохранение доп информации в свяжующую таблицу

### ISSUE THREAD

**Issue by koroleveduard** [voskobovich/yii2-many-to-many-behavior#28]
У меня в таблице cat_2_product есть поле main которое обозначает главная эта категория или нет.

Во вьюхе у меня есть список чекбоксом со всеми категориями, отмеченные те из них, к которым относится продукт.
И я хочу список отмеченных категорий, в котором среди них выбираешь одну главную.
Общий список я получаю вот так:
```
<?= $form->field($model, 'category_ids')
        ->checkBoxList(
                ArrayHelper::map(Category::find()->all(), 'id_category', 'name')
                //,['multiple' => 'true']
            );
        ?>
```

главную категорию вывожу так:
```
<?= $form->field($model, 'main')
        ->dropDownList(
                ArrayHelper::map($model->main, 'id_category', 'name')
            );
        ?>
```

При клике на чекбоксы я javascript'ом удаляю из второго списка все элементы, и добавляю туда все отмеченные в первом.

В модели поле main получается так:
```
public function getMain()
    {
        return $this->hasMany(Category::className(), ['id_category' => 'id_category'])
             ->viaTable('{{%cat_2_product}}', ['id_product' => 'id_product'],function($query){
                $query->andWhere([
                    'main' => '1',
                ]);
                return $query;
             });
    }
```

Подскажите плиз как сохранить 1 в поле main одной из строк связующей табл

**Comment by voskobovich** [comment]
Моя команда решала подобную задачу совсем не давно.
После долгих размышлений мы пришли к выводу, что лучше всего опираться на порядок передаваемых категорий - первая переданная с клиента категория является главной.

Исходя из этого конфигурация поведения имеет следующий вид:
```
'manyToManyBehavior' => [
    'class' => ManyToManyBehavior::className(),
    'relations' => [
        'category_ids' => [
            'categories',
            'fields' => [
                'string' => [
                    'get' => function ($value) {
                        return implode(',', array_map('intval', $value));
                    },
                    'set' => function ($value) {
                        if (empty($value)) {
                            return [];
                        }
                        return array_map('intval', explode(',', $value));
                    },
                ]
            ],
            'viaTableValues' => [
                'is_main' => function ($model, $relationName, $attributeName, $relatedPK) {
                    return $model->category_ids[0] == $relatedPK;
                },
            ],
        ],
        'link_block_post_ids' => 'linkedPosts',
    ],
],
```
Код взят из реального проекта.

Но дальше, потребовался нормальный control для управления всем этим делом.
Так как категории хранятся в виде дерева используя [behaviors](http://habrahabr.ru/post/266155/) @paulzi и мой виджет для управления деревом [tree manager](https://github.com/voskobovich/yii2-tree-manager) то нами был создан еще один виджет для привязки категорий к посту с возможностью управлять сортировкой категорий и выбором главной (первая из спика).

В данный момент виджет тестируется и я не успел еще выложить его, но если он тебе понадобиться - я оформлю репо в течении пары дней.

Почему мы выбрали это решение?
Потому что только этот вариант позволяет работать в обе стороны:

- вычислить главную категорию на сервере из списка переданных с клиента
- вычислить главную категорию на клиенте переданных с сервера

Все остальные варианты с созданием доп. полей и попытки их заполнять с сервера начали порождать кучу костылей и мы от них оказались в пользу вышеописанного способа.

**Comment by voskobovich** [comment]
Как движется решение задачи?

**Comment by koroleveduard** [comment]
нормально, перенёс свойство это из связующей таблицы в таблицу с 
продуктами. Все категории будут доставаться из связыющей, а главная для 
роутинга будет доставаться из самой модели продукта.

**Comment by voskobovich** [comment]
Это заставило тебя сделать два отдельных контрола для главной категории и для остальных. Такой подход конечно работает, но он много вопросов порождает у пользователей, а потом и проблем)

**Comment by koroleveduard** [comment]
нет, зачем?
у меня есть 2 сущности:
продукт
категория
под каждую у меня:
контроллер
вьюха.
Даже по 2, для бекенда и для фронтенда.
И у меня есть связующая таблица. Вот и всё.
В контроллер у меня обычные действия - добавить удалить редактировать

**Comment by voskobovich** [comment]
Я не контроллеры имел ввиду, а контролы (form control -англ - элемент управления).
С таким подходом тебе пришлось сделать 2 контрола в форме.
Что-то типа:
1. Категории
2. Главная категорий
Как ты юзеру объяснишь, что главная участвует для хлебных крошек и для прочей логики, а "Категории" это реальный список категорий с которыми связан продукт. Можно подсказку написать. Но тогда может случится исключительная ситуация.
Юзер выбрал:
Категории = Б, В, Г, Д
Главная категория = A
Как видишь, главной категории нет в реальном списке категории.
Тогда может SEO пострадать из-за не правильных ссылок и прочего.
В общем, просто будь внимателен - твое решение является узким местом со сложной логикой для пользователя.

**Comment by koroleveduard** [comment]
нет, в главной категории доступны для выбора только те которые отмечены 
в списке категорий. Если ты снимаешь какие то категории то список в 
главной перестраивается.
По поводу знания - ну у нас сео компания)) так что всё ок) Мы этот 
функционал переодически напиливаем на другие cms.

**Comment by voskobovich** [comment]
А, ну тогда хорошо)
