### ISSUE TITLE
Сохранение связанных моделей перед сохранением главной модели 

### ISSUE THREAD

**Issue by MickeyUr** [voskobovich/yii2-many-to-many-behavior#30]
Здравствуйте, не могли бы Вы подсказать, как перед сохранением модели к которой я цепляю ваш бихевиор сохранить модели с которыми она связана? 
Наведу пример. например у пользователя может быть много адресов, имеется модель адрес, связь через доп таблицу. можно ли дать возможность пользователю добавлять адреса и тут же их цеплять по id ?

**Comment by voskobovich** [comment]
Странный вопрос.
Мое поведение как раз и отвечает за связь моделей между собой.
Что конкретно не получается?

**Comment by MickeyUr** [comment]
Спасибо, уже разобрался. Сделал как по примеру вот здесь http://wbraganca.com/yii2extensions/dynamicform-demo1/source-code
как я понимаю ваш бихейвиор не предназначен для такого а просто сохраняет связи между моделями, я правильно понял ?

**Comment by voskobovich** [comment]
Совершенно верно. Мое поведение сохраняет связи между существующими моделями.

**Comment by MickeyUr** [comment]
Спасибо за пояснения
