### ISSUE TITLE
валидация входных данных

### ISSUE THREAD

**Issue by iamserjo** [voskobovich/yii2-many-to-many-behavior#34]
У меня получилось добавить связь с несуществующей записью и с NULL. Есть ли рабочая проверка?

**Comment by voskobovich** [comment]
А разве поведение должно отвечать за валидацию данных?
За валидацию отвечает модель или база.

**Comment by iamserjo** [comment]
Ну вообще было бы логично, что many many должно быть целостное.
А как лично вы валидируете данные?

**Comment by voskobovich** [comment]
Я настраиваю внешние ключи в БД и если чет будет не так - она кинет эксепшн.
Можно валидатор написать кастомный чтобы проверял и давал нормальные ошибки. 
Смотря в какой ситуации и для чего это нужно.
