### ISSUE TITLE
Полная перезапись всех связующих записей при добавлении/удаление хотя бы одной

### ISSUE THREAD

**Issue by nikstudio2000** [voskobovich/yii2-many-to-many-behavior#36]
Проблема вот в чем:
Есть таблица A, есть таблица B. связаны они via таблицу AB. Помимо основных полей для связи, есть в AB поле created_at.
По идее, в нем сохраняется время добавление конкретной связи. Но в случае обновления списка связей все они удаляются и создаются заново, тем самым обретают дружно одинаковое значение поля created_at, и смысл его существования теряется.

**Comment by voskobovich** [comment]
Есть идеи как решить?

**Comment by nikstudio2000** [comment]
Ну видится два выхода:
1. При обновлении родительской модели (A или B) проверять записи-связи (AB): старые не трогать, а добавлять только новые или удалять лишние.
2. Модификация первого варианта - сохранить в памяти все что были, со значениями доп. атрибутов, добавить новые к списку, удалить лишние, из таблицы удалить все (как сейчас) и добавить весь новый список целиком.

**Comment by voskobovich** [comment]
Первый вариант с проверками и разбирательством порождают запросы в базу, что не очень хорошо.
Второй уже более приемлем.
Сделаешь pull request со вторым вариантом?

**Comment by arogachev** [comment]
@nikstudio2000 Не подумайте, что навязываю другое решение, но я такое реализовал уже давно в своём аналогичном расширении - https://github.com/arogachev/yii2-many-to-many.

В нем изменяется в базе только то, что действительно изменилось.

**Comment by voskobovich** [comment]
@arogachev отличное решение.
На днях отрефакторю свое поведение и подготовлю новую версию с обновленной логикой.
@nikstudio2000 ты успел что-то написать по этой задаче?

**Comment by voskobovich** [comment]
@nikstudio2000 начал работать над обновлением логики.
Пришел к такому алгоритму:

1. Получаем новый список связей с формы
2. Получаем связи которые есть в базе сейчас
3. Находим связи, которых нет в базе, но пришли с формы - добавляем в базу
4. Находим связи которые есть в базе, но нет с формы - удаляем из базы
5. Проверяем связи которые пришли с формы и которые есть в базе на предмет изменения остальных атрибутов (is_main, created_at и тд) в строке. Если хоть один был изменен - связь нужно удалить и снова добавить.

Если хоть один атрибут связи был изменен - значит связь была разрушена и снова создана.

Все правильно?

**Comment by sahobanich** [comment]
Приветствую!
Очень не хватает кастомного обновления связей.
Ожидается ли обновление в ближайшее время?

**Comment by voskobovich** [comment]
@sahobanich логика была написана для сценария выше, но потом встал вопрос обратной совместимости. Нужно дать возможность выбрать какую логику юзать: старую или новую.
У тебя есть время, возможность и навыки помочь проекту? Надо будет его докодить, тогда и обновление в ближайшие дни)

**Comment by sahobanich** [comment]
Опыт у меня небольшой в разработке под yii. Могу помочь с тестированием и дать обратную связь.

**Comment by voskobovich** [comment]
@sahobanich https://github.com/voskobovich/yii2-many-to-many-behavior/tree/v3.3.0
В ветке v3.3.0 новая логика. Она прошла тесты на Trevic CI, так что можешь к себе в проект поставить.

Решения не будет пока что включено в релиз. Предлагаю тебе его доделать, получить опыт и прибавку к карме. Я помогу и расскажу как и что надо сделать. Что скажешь?

**Comment by sahobanich** [comment]
Поставлю сегодня вечером. 
Попробую помочь.
Что нужно сделать?

**Comment by voskobovich** [comment]
Нужно написать мне свой скайп на рабочую почту) Она есть на моей странице гитхаб.

**Comment by nagyt234** [comment]
It would be very good, if the communication would happen in english. But anyway, as I can determine this issue is about the problem, that all junction records will be deleted and re-created even if only one should be removed or created.
This behavior makes impossible to use foreign keys referencing the junction table. I would be glad if a junction record would remain in the database until it is deleted by the user explicitly.
I guess it is not very complicated to read the old records, create the junction table in memory, make the difference and delete old records which are not needed anymore and create new ones.

**Comment by nagyt234** [comment]
I've changed to https://github.com/arogachev/yii2-many-to-many. It solves my problem. :-)
