### ISSUE TITLE
сохранение в связующей таблице.

### ISSUE THREAD

**Issue by mozgobol** [voskobovich/yii2-many-to-many-behavior#37]
сделал все по примеру.  все более чем отлично работает, но не сохраняет именно связующие элементы. есть статьи есть категории, при сохранении статьи  -катерия не сохраняется, остается предыдущая.

**Comment by voskobovich** [comment]
Ну, значит что-то сделано не правильно.
Приведите примеры кода конфигурации поведения, связей, и правил валидации.

**Comment by mozgobol** [comment]
может быть) просто в вашем примере фраза "Все созданные поведением атрибуты необходимо упомянуть в правилах валидации. Старайтесь писать осмысленные правила, а не указывать их в группу «safe» и готово." не расписана)

**Comment by mozgobol** [comment]
view формы(сгенерировано  gii потом добавлено уже свое)
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use mihaildev\ckeditor\CKEditor;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use kartik\datetime\DateTimePicker;
use app\models\Articlecategories;
use app\models\Articlecategoryconnect;
use yii\web\JsExpression;
/* @var $this yii\web\View */
/* @var $model app\models\Articles */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="articles-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'meta_key')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'meta_desc')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'articlecategories_ids')->dropDownList(Articlecategories::listAll(), ['multiple' => true]) ?>
	
<?php
echo $form->field($model, 'prev_text')
			->widget(CKEditor::className(),['editorOptions' => ElFinder::ckeditorOptions('elfinder',
			[
				'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
        		'inline' => false, //по умолчанию false   
    		]),
]);
?>
<?php
echo $form->field($model, 'full_text')
			->widget(CKEditor::className(),['editorOptions' => ElFinder::ckeditorOptions('elfinder',
			[
				'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
        		'inline' => false, //по умолчанию false   
    		]),
]);
?>
<?php


echo $form->field($model, 'photo')->widget(InputFile::className(), [
    'language'      => 'ru',
    'controller'    => 'elfinder', // вставляем название контроллера, по умолчанию равен elfinder
    'path' => '', // будет открыта папка из настроек контроллера с добавлением указанной под деритории 
    'filter'        => 'image',    // фильтр файлов, можно задать массив фильтров https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#wiki-onlyMimes
    'template'      => '<div class="input-group">{input}<span class="input-group-btn">{button}</span></div>',
    'options'       => ['class' => 'form-control'],
    'buttonOptions' => ['class' => 'btn btn-default'],
    'multiple'      => false       // возможность выбора нескольких файлов
]);
?>

   

    <?=$form->field($model, 'tags')->textInput(['maxlength' => true]) ?>

    <?php
    
    echo $form->field($model, 'date')->widget(DateTimePicker::classname(), 
    	[
			'options' => ['placeholder' => 'Введите дату события...'],
			'pluginOptions' => [
			'autoclose' => true,
			'format' => 'yyyy-mm-dd hh:ii:ss'
		]
	]);
    ?>

    <?=
    $form->field($model, 'publish')->dropDownList([
    '1' => 'Активный',
    	'0' => 'Отключен'
	]);
    
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

**Comment by mozgobol** [comment]
модель статьи `<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%articles}}".
 *
 * @property string $id
 * @property string $title
 * @property string $meta_key
 * @property string $meta_desc
 * @property string $prev_text
 * @property string $full_text
 * @property string $photo
 * @property string $tags
 * @property string $date
 * @property integer $publish
 */
class Articles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%articles}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'meta_key', 'meta_desc', 'prev_text', 'full_text', 'photo', 'tags', 'publish'], 'required'],
            [['prev_text', 'full_text'], 'string'],
            [['date'], 'safe'],
            [['publish'], 'integer'],
            [['title', 'meta_key', 'meta_desc', 'photo', 'tags'], 'string', 'max' => 255]
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => \voskobovich\behaviors\ManyToManyBehavior::className(),
                'relations' => [
                    'articlecategories_ids' => 'articlecategories',
                ],
            ],
        ];
    }
	public function getArticlecategories()
    {
        return $this->hasMany(Articlecategories::className(), ['id' => 'articlecategories_id'])
             ->viaTable('{{%articlecategoryconnect}}', ['articles_id' => 'id']);
    }

    public static function listAll($keyField = 'id', $valueField = 'title', $asArray = true)
    {
        $query = static::find();
        if ($asArray) {
                $query->select([$keyField, $valueField])->asArray();
        }

        return ArrayHelper::map($query->all(), $keyField, $valueField);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'meta_key' => 'Meta Key',
            'meta_desc' => 'Meta Desc',
            'prev_text' => 'Краткий текст',
            'full_text' => 'Полный текст',
            'photo' => 'Фотография',
            'tags' => 'Теги',
            'articlecategories_ids' => 'Категория',
            'date' => 'Дата',
            'publish' => 'Опубликовано',
        ];
    }
    
}
`

**Comment by mozgobol** [comment]
контроллер статьи
```
<?php

namespace backend\controllers;

use Yii;
use app\models\Articles;
use app\models\Articlecategories;
use app\models\Articlecategoryconnect;
use app\models\ArticlesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use mihaildev\ckeditor\CKEditor;
use kartik\datetime\DateTimePicker;
use mihaildev\elfinder\InputFile;
use mihaildev\elfinder\ElFinder;
use yii\web\JsExpression;
/**
 * ArticlesController implements the CRUD actions for Articles model.
 */
class ArticlesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
    
    public function actions()
{

}

    /**
     * Lists all Articles models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ArticlesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Articles model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Articles model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {	

        $model = new Articles();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    


    /**
     * Updates an existing Articles model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {    
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Articles model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Articles model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Articles the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Articles::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

```

**Comment by mozgobol** [comment]
если поможете раз, буду признателен, запомню и больше приставать не буду)

**Comment by mozgobol** [comment]
таблицы:
 articles (id,title,...),
 articlecategories (id,title,...),
articlecategoryconnect (id,articlecategories_id,articles_id)
ну и модели соответствующие сгенерированые gii

**Comment by voskobovich** [comment]
Вы знаете тот факт, что если атрибут модели не упомянут ни в одном из правил валидации, то он не будет заполняться с формы?
Ваш атрибут `articlecategories_ids` не упомянут в правилах. Данные с формы в него не будут попадать и связи не будут сохраняться.

> Именуйте атрибуты более осмысленно
Лучше назвать не `articlecategories_ids`, а `categories_ids`.
Связь тоже лучше переименовать с `getArticlecategories()` на `getCategories()`

PS: Если мой ответ помог, поставьте звезд на моих репозиториях в GitHub.

**Comment by mozgobol** [comment]
мнда, не дошло) спасибо!

**Comment by mozgobol** [comment]
последний вопрос и закрываю - как звезд вам поставить тут? не вижу

**Comment by voskobovich** [comment]
На главной странице каждого репозитория в верхнем правом углу есть кнопка *Start*. На нее нужно клацнуть. Одному репозиторию можно поставить только одну звезду.

**Comment by mozgobol** [comment]
понятно, поставил, большое спасибо!
