### ISSUE TITLE
вывод связанных элементов во view и gridview

### ISSUE THREAD

**Issue by mozgobol** [voskobovich/yii2-many-to-many-behavior#38]
Добрый вечер. Освоился с вашей разработкой, безумно удобная вещь. Но вот есть у меня задача, допустим, есть поля тренинги и занятия. Все сгенерировано в основном gii, и добавлен функционал по примеру. Хотелось бы в представлении занятия view или index(там стандартный виджет grid view) вывести значения связанных элементов через связанную таблицу. То есть чтобы в списке занятий показывался заголовок тренинга, и наоборот

**Comment by voskobovich** [comment]
Спасибо за отзыв)
В чем проблема сделать описанное?
Моё поведение только помогает сохранять связи между объектами и не отменяет стандартный функционал фреймворка)
Как работать со связями описано в документации.

**Comment by mozgobol** [comment]
проблема в том, что в документации я не нашел как вывести значения используя связи, но не в форме

**Comment by voskobovich** [comment]
Вот здесь описано пошагово что нужно сделать 
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#relational-data

**Comment by voskobovich** [comment]
Вопрос решен? Могу закрывать ветку?

**Comment by mozgobol** [comment]
да, конечно) Давно уже, простите) Вам спасибо большое
