### ISSUE TITLE
Сортировка в связующей таблице.

### ISSUE THREAD

**Issue by loveorigami** [voskobovich/yii2-many-to-many-behavior#43]
Есть таблица А (товары) и таблица B(группы - "новинки", "акции" и тп.). Связь - многие-ко-многим.
В каждой группе один и тот же товар должен выводится в разном порядке: в новинках - первым, в акциях - пятым.

Создал связующую таблицу AB с полем order.
Вот тут и загвоздка. Как выполнить сортировку?

---

В одном проекте делал сортировку для тегов.
Получал модели AB, заносил в поле с виджетом -> http://selectize.github.io/selectize.js/ (вкладка plugins->drag_drop). Все отсортировал (добавил, удалил). Отсортированные данные потом в таком же порядке обновлял, проставляя  новые номера https://github.com/loveorigami/lo-core/blob/master/behaviors/TaggableStr.php#L180

---

Можно ли в Вашем поведении выполнить сохранение `viaTableValues` типа order?

**Comment by voskobovich** [comment]
Не заметил ваш Issue.
Вчера выкатил новую ветку "linker" в которой можно будет писать свою логику обработки сохранения связей.

Пока что она не релизнута, так как требует некоторых доработок. Но в качестве эксперимента можеет поставить ее себе и помочь мне с тестированием)

1. Поведение будет переименовано
1. Добавлена возможность задавать собственный обработчик сохранения связей, где вы сможете доработать его до нужного поведения.

**Comment by loveorigami** [comment]
Пользуюсь Вашим поведением - все очень удобно реализовано.
Свою задачу я решил более прагматично, поджимали сроки ).
Сделал на связующую таблицу модель, подключил grid с виджетом x-editable для позиций.

Новое поведение обязательно потестирую через пару дней. О результатах - отпишусь.

**Comment by voskobovich** [comment]
Привет! Вышла новая версия поведения [Yii2 Linker Behavior](https://github.com/voskobovich/yii2-linker-behavior). Прошу начать использовать в новых проектах!
