### ISSUE TITLE
BatchInsert with more than 1000 rows

### ISSUE THREAD

**Issue by thejahweh** [voskobovich/yii2-many-to-many-behavior#45]
I use MSSQL and get the error:

```
The number of row value expressions in the INSERT statement exceeds the maximum allowed
number of 1000 row values.
```

To solve the problem we have two solutions:
1. Don't delete all rows, just delete the not anymore used ones and insert just the new ones.
2. Do a `array_chunk($junctionRows, 1000)` and then the batchInsert on the arrays.

I would recommend to implement both solutions.

**Comment by voskobovich** [comment]
Yes, I know about this problem. In developing the second version which doesn't pass the tests and cannot be released. There is a desire, see branch "linker". I will be glad for your help.

**Comment by thejahweh** [comment]
As far as I can see it in the new `linker` version the problem is just that the default value is not given to the `OneToManyUpdater`.

**Comment by voskobovich** [comment]
Hi! Released the new version of behavior. It's already available for use on the link [Yii2 Linker Behavior](https://github.com/voskobovich/yii2-linker-behavior).

In the new version solve your problem easier.
