### ISSUE TITLE
created_at and updated at

### ISSUE THREAD

**Issue by zmoddynamics** [voskobovich/yii2-many-to-many-behavior#46]
Hi, Thank you for creating this very useful extension. I have a minor issue which isn't a huge deal for my application but was hoping for your thoughts. Following your guidance, I am using the viaTableValues as shown below:

`'relations' => [
                    'variable_ids' => [
                        'variables',
                        'viaTableValues' => [
                            'created_at' => function($model, $relationName, $attributeName, $relatedPk) {
                                return $model->isNewRecord ? time(): $model->created_at;
                            },
                            'updated_at' => function() {
                                return time();
                            },
                        ],
                    ]
],`

Upon record creation, the updated_at and created_at times are slightly different. Any suggestions? I also notice, that even if I do not change the attribute value for say variable_id, the updated_at time changes ?

**Comment by voskobovich** [comment]
Yes, I know about this problem. In developing the second version which doesn't pass the tests and cannot be released. There is a desire, see branch "linker". I will be glad for your help.

**Comment by zmoddynamics** [comment]
Thanks. I will probably also create a pull request for another feature to be added as well. I’ll see if I can help you as I would like the default behavior of TimeStamp within the extension.

**Comment by voskobovich** [comment]
Hi! Released the new version of behavior. It's already available for use on the link [Yii2 Linker Behavior](https://github.com/voskobovich/yii2-linker-behavior).

The new version solved your problem.

**Comment by zmoddynamics** [comment]
Thanks. I'll check it out.

Clint Zeringue, PhD
ZModDynamics
CEO & President
Mobile (225) 636-8252<tel:(225)%20636-8252>

On Nov 29, 2016, at 8:03 AM, Vitaly Voskobovich <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! Released the new version of behavior. It's already available for use on the link Yii2 Linker Behavior<https://github.com/voskobovich/yii2-linker-behavior>.

The new version solved your problem.

-
