### ISSUE TITLE
Не сохраняет в связную таблицу

### ISSUE THREAD

**Issue by xelaxela13** [voskobovich/yii2-many-to-many-behavior#49]
Перечитал мануал несколько раз, перепробовал много вариантов, не работает

```
<?php

namespace app\models;


use voskobovich\behaviors\ManyToManyBehavior;
use voskobovich\linker\LinkerBehavior;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Url;
use yii\web\HttpException;
use yii\web\IdentityInterface;

class Users extends \yii\db\ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_NOTACTIVE = 0;
    const USER_AUTHOR = 0;
    const USER_ADMIN = 1;

    public $password;
    public $password_repeat;
 
    public static function tableName()
    {
        return 'users';
    }

 
    public function rules()
    {
        return [
            [['status', 'role', 'created_at', 'updated_at'], 'integer'],
            [['username', 'email', 'password_hash', 'password_reset_token', 'auth_key'], 'string', 'max' => 255],
            [['password_hash'], 'unique'],
            [['auth_key'], 'unique'],
            ['email', 'unique'],
            ['status', 'default', 'value' => self::STATUS_NOTACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED, self::STATUS_NOTACTIVE]],
            ['role', 'default', 'value' => self::USER_AUTHOR],
            ['role', 'in', 'range' => [self::USER_AUTHOR, self::USER_ADMIN]],
            ['password', 'compare', 'message' => Yii::t('app', 'Repeat password')],
            ['password_repeat', 'compare', 'compareAttribute'=>'password', 'message' => Yii::t('app', 'Passwords do not match.')],
            ['password', 'required'],
            ['password', 'string', 'min' => 6],
            [['user_id'], 'safe'],

        ];
    }
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {

            $this->username = $this->email;

            return true;
        }
        return false;
    }
    public function behaviors()
    {
        return [
            [
                'class' => LinkerBehavior::className(),
                'relations' => [
                    'user_id' => 'usersmeta',
                ],
            ],
            TimestampBehavior::className(),
        ];
    }

    public function getUsersmeta()
    {
        return $this->hasMany(Usersmeta::className(), ['user_id' => 'id']);
    }
```

в модели Usersmeta

`public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }`
 
две таблицы
users и usersmeta
в usersmeta - id, user_id, name, lastname, phone 
id - primary key
user_id  - index
я же понимаю связи в базе не обязательно настраивать, хотя и пробовал, не помогла...

где может быть ошибка?

**Comment by voskobovich** [comment]
А что именно не работает-то?
Что настраивалось, что ожидали и что получилось?

Смею предположить, что проблема в 
```
'user_id' => 'usersmeta',
```
так как должно быть
```
'user_ids' => 'usersmeta',
```
У вас в модели уже занят атрибута `user_id`, а значит повторно он создан быть не может. Для этого называем новый атрибут `user_ids`.

**Comment by xelaxela13** [comment]
то есть, в таблице ячейка называется user_id, и в нее я хочу записать id вновь созданного user'a,
а писать нужно 
```
'relations' => [
                    'user_ids' => 'usersmeta',
                ],
```
и в rule соответствено?

**Comment by xelaxela13** [comment]
и еще не понятно, во view в форму обязательно вставлять поле 
```
<?= $form->field($model, 'user_ids')
    ->dropDownList($usersmetaAsArray, ['multiple' => true]) ?>
```
и не ясно откуда берем $usersmetaAsArray

**Comment by voskobovich** [comment]
Чтобы я смог что-то подсказать, мне нужна сформулированная задача и входные данные.

> Например: Мне нужно связать Юзера и Заказы. У меня в БД есть таблица user и order. У одного заказа может быть один юзер, а у юзера много заказов.

**Comment by xelaxela13** [comment]
я хочу что бы при добавлении нового пользователя (модель users), автоматически создавалась запись в модели usersmeta и в ней в ячейки user_id => id с модели users, у одного юзера много юзермета, у одной юзермета только один юзер. 
и сооотетственно при удалении пользователя, автоматически удалялись записи usersmeta
без промежуточных таблиц.

**Comment by voskobovich** [comment]
Ок. У тебя есть форма для созания юзера, в ней *должен быть* выпадающий список (multiple dropdown) для выбора вариантом Usersmeta (которые должны быть созданы ранее).

Далее. Так как мы связываем User с Usersmeta, у модели User должна быть связь (relation) к получению всех привязанных Usersmeta. Наверняка она называется как то так `usersmetas` то есть метод `getUsersmetas()`.

Далее. Настраиваем поведения у модели User.
```
    public function behaviors()
    {
        return [
            [
                'class' => LinkerBehavior::className(),
                'relations' => [
                    'usersmetas_ids' => 'usersmetas',
                ],
            ],
            TimestampBehavior::className(),
        ];
    }
```
при такой конфигурации у модели User появиться новый атрибут `usersmetas_ids` для него нужно прописать рулы как в доке.

Создаем поле на форме 
```
<?= $form->field($model, 'usersmetas_ids')
    ->dropDownList($usersmetaAsArray, ['multiple' => true]) ?>
```
Вот так все должно работать.

**Comment by xelaxela13** [comment]
выдает ошибку Undefined variable: usersmetaAsArray
controller
 ```
public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post())){
            $model->setPassword($model->password);
            $model->generateAuthKey();
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
```
views

 ```
<?= $form->field($model, 'user_ids')
        ->dropDownList($usersmetasAsArray, ['multiple' => true]) ?>
```
model

```
 public function behaviors()
    {
        return [
            [
                'class' => LinkerBehavior::className(),
                'relations' => [
                    'user_ids' => 'usersmetas',
                ],
            ],
            TimestampBehavior::className(),
        ];
    }
```
 ```
 public function getUsersmetas()
    {
        return $this->hasMany(Usersmeta::className(), ['user_id' => 'id']);
    }
```
```
public function rules()
    {
        return [
            [['user_ids'], 'safe'],

        ];
    }
```

**Comment by voskobovich** [comment]
Это не ошибка моего повередения. Переведи текст ошибки и подумай как исправить.

**Comment by xelaxela13** [comment]
в продолжении вчерашнего разговора...
ошибку нашел...
```
/**
 * This is the model class for table "users".
 *
 * @property Usersmeta[] $usersmetas
 */
```
views

```
<?= $form->field($model, 'user_ids')
       ->dropDownList($model->usersmeta, ['multiple' => true]) ?>
```
только ничего не происходит, в базу добавляется новый пользователь, а в связную таблицу usersmeta ничего не создается... (на момент создание пользователя в таблице Usersmeta нет ниодной записи) 
может есть мысли по этому поводу?

**Comment by voskobovich** [comment]
Мысли есть. Я выше писал, что мое поведения связывает сущьности, а не создает новые.
И так же, выше я писал, что 
> Ок. У тебя есть форма для созания юзера, в ней должен быть выпадающий список (multiple dropdown) для выбора вариантом Usersmeta (которые должны быть созданы ранее).

обрати внимание на слова **должны быть**.

Другими словами, мое поведение помогает привязать существующий usersmeta к создаваемому юзеру.

Это как привязать:
- существующие категории к создаваемому посту
- существующего клиента в новому заказу
