### ISSUE TITLE
Какм сохранить запись в связаной табл. после обновления

### ISSUE THREAD

**Issue by gosh1985** [voskobovich/yii2-many-to-many-behavior#50]
Есть таблицы news, tag_lib и связующая tag_news. С помощью поведения ManyToMany при создании новой записи News,
 в таблицу tag_news добавляется новая запись и все работает хорошо, но когда пытаюсь просто изменить например 
значение количества посещений новости(таблица news), то запись таблицы tag_news, связаная с этой новостью исчезает.
Поведение вот так подключил:

    public function behaviors()
  {
      return [
        'manyToMany' =>  [
              'class' => \app\components\ManyHasManyBehavior::className(),
              'relations' => [
                  'tags' => 'tag_list',

                  ],
              ],

      ];
  }
Как можно оставить связаную запись tag_news ,без изменения?

**Comment by voskobovich** [comment]
Скорее всего запись исчезает потому что поведению передается пустой масив с формы.
```
Model[tags] = []
```
Поведение считает что при обновлении попросили убрать связи и удаляет их. 
Чтобы связи оставались, ножно либо не передавать вообще ничего либо передать список связей заново
```
Model[tags] = [1,2,3]
```

**Comment by gosh1985** [comment]
Я кликаю на значек, отправляется ajax  вроде такого   /news/ratingplus?id=3, принимает такой вот метод контролера News:
public function  actionRatingplus($id){
      $model = new News();
              $row = News::findOne($id);
              $row->rating_plus = $row->rating_plus + 1;
              $row->save;
список здесь в save() передавать? типа :     $row->save(true,['tag_id','news_id']);
или это в моделе делается както:
'tags' => [
    'tags_list',
    'default' => function($model, $relationName, $attributeName) {
        //default value calculation
        //...
        return $defaultValue;
    },
],
А можно вообще отключать поведение, ведь в моем случае оно покачто нужно только в админке, когда создается новая запись в табл. news.

**Comment by voskobovich** [comment]
Нет, при такой конфигурации связи не должны удаляться.
И ничего в save() метод не нужно дополнительно для поведения передавать.

Нужно просто понимать логику поведения и отдебажить код свой.
Поведение работает вот так:
1. Если передан пустой массив
    ```
    $model->tags = []
    ```
    поведение посчитает что модель **не должна** быть связана и удалить все записи из таблицы связей.

1. Если передан массив значение
    ```
    $model->tags = [,1,2,3]
    ```
    поведение посчитает что модель **должна** быть связана и приведет список связей к нужному виду. Удалит лишние связи и добавить новые, если нужно.

1. Если свойство вообще не заполнено
    ```
    unset($model->tags);
    ```
   поведение проигнорирует обработку этого свойства и связи останутся **не тронуты**. Все что было в таблице останется без изменений.

А дальше смотри в правилах валидации, может `default` значение есть. Может где-то из других мест приходит пустое значение.

**Comment by GSpecDrum** [comment]
Как мне удалить связи при помощи вашего поведения? Как с формы передать пустой массив? У меня сейчас, если поле пустое, то в пост-запрос ничего не передается, и связи не удаляются.

**Comment by artem78** [comment]
У меня такая же проблема. Модель:
```class Module extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'modules';
    }

    public function behaviors()
    {
        return [
            [
                'class' => \app\components\behaviors\ManyHasManyBehavior::className(),
                'relations' => [
                    'offers' => 'offer_list',
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['active'], 'boolean'],
            [['file_name'], 'required'],
            [['file_name'], 'string', 'max' => 64],

            [['offer_list'], 'safe'],
        ];
    }

    // ...

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOffers()
    {
        return $this->hasMany(Offer::className(), ['id' => 'offer_id'])->viaTable('modules_offers', ['module_id' => 'id']);
    }
}
```

Сброс связей возникает в этом методе контроллера:
```
    public function actionActivate($value = true) {
        $id = Yii::$app->getRequest()->getQueryParam('id');
        if ($id) {
            $module = Module::findOne($id);
            $module->active = $value;
            $module->save();
        }
        return $this->redirect(['index']);
    }
```

Как видите значение `offer_list` нигде не меняю, но сброс происходит. С чем может быть это связано?

**Comment by voskobovich** [comment]
@GSpecDrum могу увидеть как построена форма?
Форма должна быть построена через ActiveForm компонент. Он знает как строить формы так, чтобы отправлялся пустой массив при пустом значении контрола)

**Comment by voskobovich** [comment]
@artem78 мне нужно видеть, что вы отправляете на сервер в запросе который чистит таблицу. Сделайте скриншот из панели дебага браузера.

**Comment by voskobovich** [comment]
@artem78 связано может быть с багом, который закрался в коде поведения.
Я могу подебажить на вашем проекте по TeamViewer? Если да напишите мне на емей (в профайле гитхаба).

**Comment by artem78** [comment]
@voskobovich Проблема возникает не в форме (там всё прекрасно работает), а в действии контроллера смены статуса `activate` (фрагмент кода уже привёл выше). Отправляю GET запрос: http://localhost/Leadvertex/yiicrm/web/module-dispatcher/activate?id=3

**Comment by voskobovich** [comment]
@artem78 Не по теме, но все же.
Вы делаете грубую ошибку, меняя объекта GET запросом. GET запрос не должен ничего менять, создавать или удалять. Для вашей задачи правильно использовать POST.

**Comment by artem78** [comment]
@voskobovich Спасибо за замечания, в Yii я пока что новичёк. Просто у меня информация об объектах выводится через GridView с ссылками активировать/деактивировать в каждой строке, поэтому использовал GET.

**Comment by voskobovich** [comment]
@artem78 нужно использовать JavaScript для правильно реализации. 
В GridView кнопка удаления реализована черещ JS и работает через POST запрос, хотя тоже сделана как ссылка. Посмотрите реализацию там и сделайте так же. Там вроде решается путем добавления data-параметра к ссылку чтобы она отправлялась через POST средствами Yii2.

**Comment by artem78** [comment]
@voskobovich Попробую так сделать. А это может помочь решить проблему со связями?

**Comment by voskobovich** [comment]
@artem78 нет, это не решит проблему.
Для решения проблемы нужно дебажить, что я и предлагал сделать прямо на вашем проекте. Писал в сообщении выше об этом.

**Comment by artem78** [comment]
@voskobovich Могу закинуть на хостинг и дать вам ftp доступ.

**Comment by voskobovich** [comment]
@artem78 да, давай. Хоть так. Отправь на почту доступы, я завтра в течении дня посмотрю.

**Comment by artem78** [comment]
Хорошо, в личку напишу чуть позже.

**Comment by voskobovich** [comment]
@artem78 Мне не понятно, почему ты пишешь issue к моему поведению, если используешь не его? У тебя в папке компонентов было самописное поведение, а моего не было даже установлено в проекте. Как так?

Я сделал всего 3 правки:

1. Удалил твое поведение
2. Установил свое
![image](https://user-images.githubusercontent.com/4508703/28492618-6e50d220-6f0f-11e7-8093-2d398b13c98b.png)
3. Отредактировал модель и вьюху
![image](https://user-images.githubusercontent.com/4508703/28492589-f8bbb1ec-6f0e-11e7-9799-a1d9af243231.png)
![image](https://user-images.githubusercontent.com/4508703/28492613-5e4bbc14-6f0f-11e7-8a21-ea102dd838c0.png)



и все заработало как надо. Как же так?

**Comment by voskobovich** [comment]
@artem78 я тебе рекомендую использовать новое поведение yii2-linker-behavior из моего профиля, вместо yii2-many-to-many-behavior

**Comment by artem78** [comment]
@voskobovich 

> было самописное поведение

Не самописное, а взятое [отсюда](http://fancode.ru/post/yii2-behaviors-many-to-many). Если это не твоё, извини, значит я что-то перепутал :) Во всяком случае спасибо за помощь. Новое поведение также попробую.

**Comment by voskobovich** [comment]
@artem78 мда. Там же автор пишет, что мое поведение какашка и он может сделать лучше. Ну вот и сделал. Он удалил 90% кода и думал что все будет работать как надо. Чудак :)
В общем не ведись на тот развод, а используй **новое** поведение [**Yii2 Linker Behavior**](https://github.com/voskobovich/yii2-linker-behavior).

**Comment by voskobovich** [comment]
@artem78 и на будущее. Всегда ставь пакеты покрытые тестам и через композер. Тот способ как у него "положить в папку" это прямой путь в гроб твоего проекта :)

**Comment by voskobovich** [comment]
@gosh1985 ты тоже используешь не мой компонент, а глючную подделку!
```
'class' => \app\components\ManyHasManyBehavior::className(),
```
Установи мой компонент по оффициальной инструкции и будет тебе счастье.
