### ISSUE TITLE
Не работает поведение

### ISSUE THREAD

**Issue by Seeman13** [voskobovich/yii2-many-to-many-behavior#52]
Здравствуйте! Не работает Ваше поведение! Несколько раз перечитал инструкцию здесь и на харбахабре. Всё сделал по инструкции!!! Как только не пробовал, что только не делал - сплошные ошибки.
Мой код:

```
// поведение
public function behaviors()
    {
        return [
            [
                'class' => \voskobovich\behaviors\ManyToManyBehavior::className(),
                'relations' => [
                    'id_hs'  => 'idH',
                    'id_bs' => 'idB',
                ],
            ],
        ];
    }
```

```
// правила
public function rules()
    {
        return [
            [['id_h', 'id_b'], 'safe'],
            [['id_hs', 'id_bs'], 'each', 'rule' => ['integer']],
    }
```

```
// связи
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdB()
    {
        return $this->hasMany(B::className(), ['id' => 'id_b']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdH()
    {
        return $this->hasMany(H::className(), ['id' => 'id_h']);
    }
```

```
// вид
<?= $form->field($ansp, 'id_hs', [
                        'inputOptions' => [
                            'class' => 'selectpicker '
                        ]
                    ])->widget(Select2::classname(), [
                        'data' => \yii\helpers\ArrayHelper::map($h, 'id', 'titel'),
                        'language' => 'de',
                        'options' => [
                            'class' => 'select2-select',
                            'multiple' => TRUE,
                        ],
                        'pluginOptions' => [
                            'allowClear' => TRUE,
                        ],
                    ]);?>
```

```
<?= $form->field($ansp, 'id_bs', [
                        'inputOptions' => [
                            'class' => 'selectpicker '
                        ]
                    ])->widget(Select2::classname(), [
                        'data' => app\modules\admin\models\B::getHierarchy(),
                        'language' => 'de',
                        'options' => [
                            'class' => 'select2-select',
                            'multiple' => TRUE,
                        ],
                        'pluginOptions' => [
                            'allowClear' => TRUE,
                        ],
                    ]);?>
````

```
// обработчик
if (Yii::$app->request->isPost && !$ansp->getErrors()) {
        $ansp->load(Yii::$app->request->post()); // загружаем данные из формы
        $ansp->save(); // просто сохраняем данные
}
```
Что я сделал не так или не по инструкции???

В итоге что? Правильно... Полный клин...
Ошибки:
```
Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
The SQL being executed was: UPDATE `b` SET `id`=1 WHERE `id` IN ('8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31')
```

И что за бредовый запрос выполняется, когда я данные хочу вставить, а не обновить!? Тоже не понятно!
При этом в таблицу БД добавляется одна строка, а не множество, как мне нужно.
К тому же данные, которые идут из формы под переменными b и h == Null, чего категорически не должно быть!

Вынужден отказаться от Вашей реализации, так как нет никакой реализации.....
Вообщем всё протестируйте, как надо, а потом выкладывайте рабочий код, чтобы люди время не теряли на "заточку" к своим проектам того, что не работает корректно!!!

**Comment by voskobovich** [comment]
Давайте по порядку.

1. У вас шаблонная задача, у поведения более 100 звед на этом ресурсе. А значит что? Правильно - с вашей задачей поведение справляется отлично и ошибка в **вашем** проекте. Плюс, поведение покрыто тестами, а это еще бошьше исключает вероятность ошибки в нем.
1. Перед тем как писать эту претензию, нужно было вспомнить, что это Open Source проект и вы можете залезть в код и найти причину самостоятельно основываясь на п.1 этого списка.
1. Вы выложили только базовые части кода и они правильные, на первый взгляд. Чтобы разобраться в чем проблема нужно еще архитектуру БД этих таблиц и классы моделей (3 штуки).
1. Запрос который выполняется реально бредовый. Вы присваиваете id=1 всем записям в таблице. Поле `id` primary key, а значит вы получаете вполне логичную ошибку. Причиной тому может быть ошибка в архитектуре связей в вашей БД.
1. Почему вы ждете какие-то значения в переменных `id_h` и `id_b`? Вы туда ничего не передаете, поведение туда ничего не пишет. Соответственно там ничего и не будет.

В итоге я могу сказать с 99% вероятностью, что ошибку нужно искать в вашем проекте. Либо соберите и выложите прототип, который я смогу запустить у себя и воспроизвести ошибку, либо сами пробегитесь дебагом и найдите проблему.

Мне очень жаль, что у вас возникли проблемы с использованием поведения :(
Если ошибка действительно есть, она будет исправлена в ближайшее время и будут внесены изменения в документацию.

И еще, попробуйте использовать https://github.com/voskobovich/yii2-linker-behavior. Это более свежая версия поведения.

**Comment by beowulfenator** [comment]
У вас связи определены неправильно. Условно назовем вашу исходную модель A.

Исходя из кода, вы намеревались создать связь 1-N между A и B (1 на стороне A, N на стороне B). Как это реализуется технически? В таблице, описывающей B, создается колонка, которая _указывает_ на таблицу A. Соответственно, каждая запись таблицы B связана с единственной записью в таблице A, но при этом одной записи в таблице A может соответствовать одна или несколько записей в таблице B.

Когда вы создаете новую запись A, на которую должны ссылаться несколько записей B, поведение обновляет записи B, потому что именно в них хранятся связи.

А как вы описали свою связь? `hasMany(B::className(), ['id' => 'id_b'])`. Из этой записи следует, что первичный ключ таблицы A называется `id_b`, а колонка в таблице B, в которой хранится ссылка на A, называется `id`. Вот почему поведение не работает. Посмотрите документацию на [`hasMany()`](http://www.yiiframework.com/doc-2.0/yii-db-baseactiverecord.html#hasMany()-detail).

Если же на самом деле вы намеревались создать между A и B связь типа N-N, то нужна [промежуточная таблица](http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#viaTable()-detail), которую нужно объявить в связи. Поведение поддерживает и этот режим.


Надеюсь, с опытом к вам придет понимание, что если какое-то расширение используется три года, имеет 28 тысяч установок и покрыто тестами, и при этом не работает лично у вас, то сперва нужно исключить ошибки на своей стороне, а только потом писать гневные отзывы на гитхабе.

**Comment by Seeman13** [comment]
Связи в БД нормальные и правильные.
Реализовал, то что требовалось мне, написав свой код с нуля. На что ушло меньше усилий и времени, чем разбор расширения поведения. Всё отрабатывает отлично!

Может быть Ваше программное решение и классное, что имеет 28 тыс. установок, но оно мне не подошло и не устроило меня, по той причине, которую я описал.

А количество не говорит о качестве - даже у платного ПО, которым пользуются миллионы есть свои минусы и баги, которыми многие могут быть не довольны.

Если обычно устанавливаешь пакеты с Github, ну если они работают, то они работают, Ваше расширение, ну никак не захотело отрабатывать в моём проекте.

Да, Вы будите утверждать, что у меня на 99% ошибка, я буду ругать расширение, нет смысла и времени всем этим заниматься и всё это выяснять. Думаю, на том, можно и закончить. Я высказал свою точку зрения, Вы свою. Но, перед тем, как писать своё сообщение, которое Вы назвали претензией, в Issues я не увидел от других пользователей вопросов чисто организационного плана. А лишь увидел вопросы типа "Не сохраняет в связную таблицу" без существенных ответов на них.

Ещё раз говорю, может быть Ваше расширение и классное, и просто пользователи, как я что-то не так делают с его использованием, но, не пошло. Напишите тогда более подробную инструкцию использования, с возможными нюансами при использовании, несколькими примерами.

Успехов Вам в разработке не только этого расширения, но и другого открытого кода. Может быть, когда-нибудь и я и решу попробовать использовать в своих проектах более свежую версию поведения, что Вы порекомендовали, если будут стоять такие задачи при разработке.
