### ISSUE TITLE
Не работает сохранение по связи many-to-many

### ISSUE THREAD

**Issue by John2013** [voskobovich/yii2-many-to-many-behavior#53]
```php
class Reservation extends \yii\db\ActiveRecord
{
	public $place_ids;

	/*...*/

	public function rules()
	{
		return [
			/*...*/
			[['place_ids'], 'each', 'rule' => ['integer']]
		];
 	}

	/*...*/

	public function getPlaces()
	{
		return $this
			->hasMany(Place::class, ['id' => 'place_id'])
			->viaTable('place_to_reservation', ['reservation_id' => 'id']);
	}

	public function behaviors()
	{
		return [
			TimestampBehavior::class,
			[
				'class' => \voskobovich\linker\LinkerBehavior::class,
				'relations' => [
					'place_ids' => 'places',
				],
			]
		];
	}
}
```

```php
        <?= $form
	        ->field($model, 'place_ids')
	        ->dropDownList(\backend\models\Place::listAll(), ['multiple'=>true]) ?>
```

При сохранении модели в связанную таблицу не сохраняется ничего, при этом нет никаких ошибок или предупреждений в логе. Вроде всё по документации делал и особо негде облажаться, но который раз пробую этот пакет каждый раз одно и то же.

Name | Value
-- | --
Yii Version | 2.0.15.1
PHP Version | 7.0.30-0+deb9u1

**Comment by John2013** [comment]
Похоже, не туда отправил, хотел отправить в LinkerBehavior, но тут у меня та же самая проблема

**Comment by voskobovich** [comment]
@John2013 удалите `public $place_ids;` в документации вроде не сказано этот шаг делать.

**Comment by John2013** [comment]
@voskobovich спасибо, в этом и была проблема
